spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://140.143.155.156:3306/dlhr
    driver-class-name: com.mysql.jdbc.Driver

server:
  #context-path: /diningcloud/
  port: 90